apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-tbk-demo-exercise-deployment
  namespace: cobranza
  labels:
    app: com-tbk-demo-exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: com-tbk-demo-exercise
  template:
    metadata:
      labels:
        app: com-tbk-demo-exercise
    spec:
      containers:
      - name: com-tbk-demo-exercise
        image: registry.gitlab.com/bs2managers/com-tbk-demo-exercise:dev
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9000
        env:
        - name: SPRING_CONFIG_URI
          valueFrom:
            secretKeyRef:
                name: spring-security
                key: configserver.host
        - name: SPRING_CONFIG_BD_URL
          valueFrom:
            secretKeyRef:
                name: spring-security
                key: bd.url
        - name: SPRING_CONFIG_BD_USERNAME
          valueFrom:
            secretKeyRef:
                name: spring-security
                key: bd.username
        - name: SPRING_CONFIG_BD_PASSWORD
          valueFrom:
            secretKeyRef:
                name: spring-security
                key: bd.password
      imagePullSecrets:
        - name: gitlab-auth-p
