apiVersion: v1
kind: Service
metadata:
  name: com-tbk-demo-exercise
  namespace: security

spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: com-tbk-demo-exercise
  type: NodePort
